# Generated by Django 5.1.2 on 2024-10-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0002_difunto_paciente_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('jefe_hospital', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='caducidad',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='edad',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='difunto',
            name='causa_muerte',
            field=models.TextField(default='Desconocida'),  # Cambiado a un valor de texto válido
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='difunto',
            name='edad',
            field=models.IntegerField(default=0),  # Cambiado a un valor entero válido
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='difunto',
            name='hora_muerte',
            field=models.TimeField(default='00:00'),  # Cambiado a un valor de tiempo válido
        ),
        migrations.AddField(
            model_name='paciente',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),  # Cambiado a un valor de texto válido
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo',
            field=models.CharField(default='General', max_length=50),  # Cambiado a un valor de texto válido
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='difunto',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='difunto',
            name='doctor_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototipo.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.especialidad'),
        ),
        migrations.AddField(
            model_name='doctor',
            name ='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.hospital'),
        ),
        migrations.AddField(
            model_name='difunto',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prototipo.hospital'),
            preserve_default=False,
        ),
    ]
