# Generated by Django 5.1.2 on 2024-10-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0003_doctor_especialidad_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
