# Generated by Django 5.1.2 on 2024-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0004_alter_paciente_caducidad_alter_paciente_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difunto',
            name='hora_muerte',
            field=models.TimeField(default=1),
        ),
    ]
